### PR TITLE
Remove Instrumentation class

### PR DESCRIPTION
**Pull request by ChrisBr**
Apparently it was used like this:

```ruby
class MetricsController < ApplicationController
  include InfluxDB::Rails::Instrumentation
  instrument :index

  def index; end
end
```

I think it is not needed anymore 🤔 @hennevogel what do you think?

### CODE REVIEW

**Review by hennevogel — CHANGES_REQUESTED** [review]
There is also a config option

**Comment by ChrisBr** [comment]
> There is also a config option

Which one? 🤔

**Comment by ChrisBr** [comment]
You mean `series_name_for_instrumentation`? We have plenty of other configurations which we did not remove in 1.0. I think we discussed back then that we keep them for one version so old versions do not crash?

**Comment by ChrisBr** [comment]
https://github.com/influxdata/influxdb-rails/blob/master/lib/influxdb/rails/configuration.rb#L73

**Comment by hennevogel** [comment]
I mean `instrumentation_enabled`

**Comment by ChrisBr** [comment]
We `instrumentation_enabled` in all our subscribers so it is either

a) unrelated to this class
b) or at some point got reused / misused

**Comment by hennevogel** [comment]
I want to solve: **B**!

**Comment by hennevogel** [comment]
I think you can just throw it out. We don't event mention it in the docu and it's on by default.

**Review by hennevogel — APPROVED** [review]

**Pull request merged**
