### PR TITLE
Do not crash if people have dropped config options...

### PR DESCRIPTION
**Pull request by hennevogel**
...YET.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Test?

**Comment by hennevogel** [comment]
I'm sure `attr_reader` is tested already :-)

**Comment by ChrisBr** [comment]
What about a deprecation message, something like:

```ruby
      # FIXME: Old configuration options, remove this in 1.0.1
      DEPRECATED_METHODS = [
        :series_name_for_controller_runtimes,
        :series_name_for_view_runtimes,
        :series_name_for_db_runtimes,
        :series_name_for_render_template,
        :series_name_for_render_partial,
        :series_name_for_render_collection,
        :series_name_for_sql,
        :series_name_for_exceptions,
        :series_name_for_instrumentation
      ]
      attr_accessor *DEPRECATED_METHODS

      UPGRADE_GUIDE_URL = "https://github.com/influxdata/influxdb-rails/wiki/1.0-Upgrade-Guide"
      ActiveSupport::Deprecation.new("influxdb-rails", "1.0.1").deprecate_methods(
        InfluxDB::Rails::Configuration,
        DEPRECATED_METHODS.map { |value| ["#{value}=", UPGRADE_GUIDE_URL] }.to_h
      )
```

**Comment by ChrisBr** [comment]
> I'm sure attr_reader is tested already :-)

Fair enough, however, you need to define `attr_writer` 😉 This will still crash when you do

```ruby
      InfluxDB::Rails.configure do |config|
        config.series_name_for_instrumentation = "series_name_for_instrumentation"
      end
```

Sometimes it's about testing to use the right internal methods 😄

**Comment by hennevogel** [comment]
> Sometimes it's about testing to use the right internal methods

:man_facepalming:

**Comment by hennevogel** [comment]
> What about a deprecation message, something like:

With the release of 0.4.99 this sounds like doppelt gemoppelt.

**Review by ChrisBr — APPROVED** [review]

**Comment by ChrisBr** [comment]
Then go for it!

**Pull request merged**
