### PR TITLE
 Do not track SQL SCHEMA queries

### PR DESCRIPTION
**Pull request by ChrisBr**

### CODE REVIEW

**Comment by dmke** [comment]
Makes sense. Can you run `rake rubocop:auto_correct` and update your last commit?

**Comment by ChrisBr** [comment]
Thanks for merging, I just saw that this was now for master :cry: Sorry... Should I create a new one targeting beta or do you cherry pick? (same for #62)

**Comment by dmke** [comment]
No, `master` is OK, I'll abandon the `1.0-beta` branch soon.

**Comment by ChrisBr** [comment]
Ok, cool! Thanks :+1: Do you plan to release another beta?

**Comment by dmke** [comment]
Yes. I'm still keen on #56 to be in at least one beta release, but last week was a bit stressful... This week I'm still busy with different things, but starting next week I'm on vacation and I can concentrate on finishing this (hopefully, that is :-D).

**Comment by ChrisBr** [comment]
Ok, cool! Enjoy your vacation :+1: : I will also be on vacation starting Friday but will be at the beach, so no more noise from my side :smile: :beach_umbrella: 

Btw: We already have beta 2 running here: https://metrics.opensuse.org/d/Gpp3B1Pik/package-show-dashboard?orgId=1 and already helped us to spot some bottlenecks :+1:

**Pull request merged**
