### PR TITLE
Add ability to extend passed tags

### LINKED ISSUE #30: write urls as well?
- Writing the urls that are being written would be interesting
- Writing current user would be interesting.

Perhaps this library should offer an easy way to control the write_point callsites?

### PR DESCRIPTION
**Pull request by Kukunin**
Fixes #30 

It's often desirable to put extra tags to the series being sent. Here is a proposal to implement it via `InfluxDB::Rails.configuration.tags_middleware`. Having a proc is much more flexible than having a static `extra_tags` hash since you can put different tags depending on current tags.

Since test coverage isn't too big, I put tests only for what is tested.

### CODE REVIEW

**Comment by dmke** [comment]
This really looks useful! Let me play a few days with it to form an educated opinion.

**Comment by dmke** [comment]
Hm... question: How would you solve #30 with this? The middleware proc doesn't have access to the controller session and hence can neither retrieve the URL nor the current user.

Am I missing something?

**Comment by Kukunin** [comment]
Yep, you're right =) It doesn't solve #30. I didn't thought about that specific case, as I had to pass extra static tags

**Comment by ChrisBr** [comment]
Anything else missing here I can help out so that we can get it in for 1.0.0?

**Comment by dmke** [comment]
Honestly, I don't know if this is actually possible. You'd need directly access to the controller *instance* in order to call methods on it. As far as I can tell, the instrumentation API isn't suitable for this.

**Comment by Kukunin** [comment]
This PR looks good IMHO to be merged at the current state. Yes, it doesn't solve #30, but it's still useful. Tell me, what prevents it from being merged, and I'll try to improve it. Thanks

**Comment by dmke** [comment]
> Yes, it doesn't solve #30, but it's still useful.

Oh, I seem to must have missed that, sorry. Can you rebase this onto the `1.0-beta` branch? I'll merge it afterwards.

**Comment by Kukunin** [comment]
@dmke here we go. Changed the base branch to `1.0-beta` as well

**Comment by dmke** [comment]
Sorry, it took a bit longer to unwind the merge commit. Here you go: https://github.com/influxdata/influxdb-rails/compare/2d9b3f6f30d4975e5e045ac3871c749f02b4195c...d846401f6b0e1ea916ef24a5c878a6f651fd56d4

**Pull request closed without merging**
