### PR TITLE
Add ability to pass a retry value to influxdb

### PR DESCRIPTION
**Pull request by bcantin**
I also added tests.

### CODE REVIEW

**Comment by jonmchan** [comment]
This feature seems useful. I would like for this PR to be merged. :+1:

**Comment by williampratt** [comment]
:+1:

**Comment by ZeroInputCtrl** [comment]
:+1:

**Comment by ericwilson29** [comment]
👍Please merge; I would like to be able to limit the number of retries.

**Comment by dmke** [comment]
I have rebased the changes onto the master branch. Tomorrow I'll check for regressions.

**Comment by dmke** [comment]
Sorry for the long silence. I have released [0.1.12](https://rubygems.org/gems/influxdb-rails/versions/0.1.12), which includes (a modified version of) this PR.

**Pull request closed without merging**
