### PR TITLE
Update initializer to use multiple hosts.

### PR DESCRIPTION
**Pull request by Peeja**
Looks like this was missed.

### CODE REVIEW

**Comment by jvshahid** [comment]
Thanks.

**Comment by toddboom** [comment]
@Peeja gracias!

**Comment by quasor** [comment]
You omitted the generator, it creates an invalid config:

```
InfluxDB::Rails.configure do |config|
  config.influxdb_database = "rails"
  config.influxdb_username = "root"
  config.influxdb_password = "root"
  config.influxdb_host     = "localhost"
  config.influxdb_port     = 8086

  # config.series_name_for_controller_runtimes = "rails.controller"
  # config.series_name_for_view_runtimes       = "rails.view"
  # config.series_name_for_db_runtimes         = "rails.db"
end
```

**Comment by Peeja** [comment]
@quasor This is the PR that fixes that issue, not the one that caused it.

**Comment by quasor** [comment]
:+1: my bad.

**Pull request merged**
