### PR TITLE
Feature/load config from file

### PR DESCRIPTION
**Pull request by lordmortis**
Load the config file from influxdb.yml

### CODE REVIEW

**Comment by lordmortis** [comment]
We've also added some other stuff, any thoughts from the influx people on this? So far haven't noticed anything not working with 0.9, but we aren't doing any queries in our app (all queries are done via nodeJS components - this is just there to do database creation when we make new accounts)

**Comment by klippx** [comment]
Is anyone maintaining this gem? I have only browsed the code and cant tell if its good or bad but it looks like good quality so I wonder why this has been here for 6 months without a comment from influxdb

**Comment by dmke** [comment]
Sorry for letting you hang for so long.

I'm going to include these changes in the upcoming 1.0 release (ETA: on the weekend).

**Comment by ChrisBr** [comment]
Should we close this one @hennevogel @dmke ?

**Comment by hennevogel** [comment]
If you *need* to do this feel free to change your initializer to read from a YAML file. I don't think we need to do this in the gem.

**Pull request closed without merging**
